import { mkdir, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateAllCssVariables } from '../../tokens/dist/index.js';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const pkgRoot = path.resolve(__dirname, '..');
const distDir = path.join(pkgRoot, 'dist');
const execFileAsync = promisify(execFile);

async function main() {
  await mkdir(distDir, { recursive: true });

  // 1) CSS variables for all themes
  const css = [
    '/* Generated by @fast/assets */',
    '/* Theme variables live under :root[data-theme="..."] */',
    generateAllCssVariables(),
    '',
  ].join('\n');

  await writeFile(path.join(distDir, 'styles.css'), css, 'utf8');

  // 1b) Compiled CSS (three separate themes) for non-Next/non-React apps.
  // We compile the existing SCSS custom files from the repo root.
  const repoRoot = path.resolve(pkgRoot, '..', '..');
  const cssBuildRoot = path.join(pkgRoot, 'css-build');
  const outCssDir = path.join(distDir, 'css');
  await mkdir(outCssDir, { recursive: true });

  async function compileThemeCss(theme: 'corporate' | 'argos' | 'atlas') {
    const inFile = path.join(cssBuildRoot, theme, 'custom.scss');
    const outFile = path.join(outCssDir, `${theme}-custom.css`);
    const outMinFile = path.join(outCssDir, `${theme}-custom.min.css`);

    // Expanded
    await execFileAsync('sass', ['--no-source-map', inFile, outFile], { cwd: repoRoot });
    // Minified
    await execFileAsync('sass', ['--no-source-map', '--style=compressed', inFile, outMinFile], { cwd: repoRoot });
  }

  await compileThemeCss('corporate');
  await compileThemeCss('argos');
  await compileThemeCss('atlas');

  // 2) Fonts (if any exist in repo root)
  // We keep this package useful even if no fonts are provided yet.
  const repoFontsDir = path.resolve(pkgRoot, '..', '..', 'fonts');
  const outFontsDir = path.join(distDir, 'fonts');
  try {
    await mkdir(outFontsDir, { recursive: true });
    await cp(repoFontsDir, outFontsDir, { recursive: true });
  } catch {
    // ignore if fonts folder is missing or empty
  }
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
